name: Save baseline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper

      - name: Build
        run: |
          ./gradlew assembleDebug --no-daemon --stacktrace -PcomposeCompilerMetrics=true -PcomposeCompilerReports=true

      - name: Retain compose compiler metrics as baseline
        id: retain-compose-compiler-metrics-as-baseline
        run: |
          for p in $(find **/build -name compose_compiler_metrics); do
            mv $p "${p}_baseline"
          done

      - uses: actions/upload-artifact@v4
        with:
          name: compose-compiler-metrics-baseline
          path: |
            **/build/compose_compiler_metrics_baseline
          retention-days: 30
